### ISSUE TITLE
Login extraParams : possiblity to add extraParams to query login

### ISSUE THREAD

**Issue by laurentC35** [garronej/oidc-spa#3]
Hello.
I am in a case where I would like to add an additional parameter to the login url (`kc_idp_hint` in my case).

Would it be possible to add this possibility with an additional parameter to OidcClient like `extraParams` which would be a key / value object.

**Comment by garronej** [comment]
Hello @laurentC35,  

Yes sure. You can set it at the root level but I can add extra param no problem

**Comment by laurentC35** [comment]
I'm not sure I understand how to do this?

I suggest adding the argument proposed by the `oidc-client-ts` library:

### Simple proposal

```js
await userManager.signinRedirect({
    redirect_uri,
    extraQueryParams: extraQueryParams,
   "redirectMethod": doesCurrentHrefRequiresAuth ? "replace" : "assign"
});

**Comment by garronej** [comment]
Adding this was indeed a must.  
Thank you for suggesting it!  

https://github.com/garronej/oidc-spa/blob/e0a009c13fc204e01bb82dbecb1730d3ba98f4bb/README.md?plain=1#L157-L158

**Comment by laurentC35** [comment]
Great, I will test this today and I'll get back to you

**Comment by laurentC35** [comment]
It works perfectly.
Thanks lot
