### ISSUE TITLE
signinRedirect should allow ExtraSigninRequestArgs

### ISSUE THREAD

**Issue by johnksv** [garronej/oidc-spa#4]
There might be use cases where the user want to specify additional oidc request args, such as `prompt`, depending on their use case and provider.
Related line is:
https://github.com/garronej/oidc-spa/tree/main/src/oidc.ts#L151C27-L151C41

**Comment by johnksv** [comment]
I see this might already have been solved by #3

**Comment by garronej** [comment]
Hey @johnksv,  
Great to see you here, anytime
