### ISSUE TITLE
Stuck in fallback component : restore_from_http_only_cookie

### ISSUE THREAD

**Issue by laurentC35** [garronej/oidc-spa#6]
Hello,

Sometimes we get stuck in the fallback component in the application when this error occurs:
```
SSO silent login timeout with clientId : xxxxx
```

It occurs sometimes when we connect from another application on the same realm, which redirects us to our application.

It happens here in the code :

```js
 restore_from_http_only_cookie: {
            const dLoginSuccessUrl = new Deferred<string | undefined>();

            const timeout = setTimeout(
                () =>
                    dLoginSuccessUrl.reject(
                        new Error(`SSO silent login timeout with clientId: ${clientId}`)
                    ),
                5000
            );
```

It is possible an cross domain error ? (cannot share cookie ?), I'm not sure

Is it possible to pass an ErrorComponent  when an Error occurs, so each client of your library can choose how to manage the error.

__NB__: when this error occurs, a simple reload of the app fix the problem for user.

Thanks for regarding 

__Using :__ `oidc-spa@2.0.3`

**Comment by garronej** [comment]
Thanks for reporting @laurentC35,  
I'll investigate with @ddecrulle
